version: "3"
services:
  hub:
    image: selenium/hub:3.141.59
  chrome:
    image: selenium/node-chrome:3.141.59
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
    volumes:
    - /dev/shm:/dev/shm
  firefox:
    image: selenium/node-firefox:3.141.59
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  book_flight_module_chrome:
    image: vishnu26121993/selenium-docker:latest
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=chrome
      - MODULE=book_flights.xml
    volumes:
      - ./output/book_flights_chrome:/usr/share/selenium-docker-automation/test-output
  book_flight_module_firefox:
    image: vishnu26121993/selenium-docker:latest
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=firefox
      - MODULE=book_flights.xml
    volumes:
      - ./output/book_flights_firefox:/usr/share/selenium-docker-automation/test-output

